# Generated by Django 5.2.7 on 2025-12-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaRestaurante',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario_id', models.IntegerField(null=True)),
                ('mesa_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'reserva_restaurante',
                'managed': True,
            },
        ),
    ]
