# Generated by Django 5.2.7 on 2026-01-09 23:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_restaurante', '0001_initial'),
        ('restaurante_mesa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservarestaurante',
            options={'ordering': ['-fecha_reserva'], 'verbose_name': 'Reserva de Restaurante', 'verbose_name_plural': 'Reservas de Restaurante'},
        ),
        migrations.RemoveField(
            model_name='reservarestaurante',
            name='mesa_id',
        ),
        migrations.RemoveField(
            model_name='reservarestaurante',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='reservarestaurante',
            name='cantidad_personas',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Comensais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservarestaurante',
            name='codigo_reserva',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Código de Reserva'),
        ),
        migrations.AddField(
            model_name='reservarestaurante',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='reservarestaurante',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservarestaurante',
            name='fecha_reserva',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora da Reserva'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservarestaurante',
            name='mesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='restaurante_mesa.restaurantemesa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservarestaurante',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Especiais'),
        ),
        migrations.AddField(
            model_name='reservarestaurante',
            name='total_reserva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservarestaurante',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_restaurante', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservarestaurante',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
