# Generated by Django 5.2.7 on 2025-11-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaDinamica',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('habitacion_id', models.IntegerField(null=True)),
                ('precio', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'tarifa_dinamica',
                'managed': True,
            },
        ),
    ]
