# Generated by Django 5.2.7 on 2025-12-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_habitacion', models.CharField(max_length=10, unique=True)),
                ('piso', models.IntegerField(choices=[(1, 'Piso 1'), (2, 'Piso 2'), (3, 'Piso 3'), (4, 'Piso 4'), (5, 'Piso 5'), (6, 'Piso 6'), (7, 'Piso 7'), (8, 'Piso 8')], default=1)),
                ('tipo_ocupacion', models.CharField(choices=[('doble', 'Doble (2 personas)'), ('triple', 'Triple (3 personas)'), ('cuadruple', 'Cuádruple (4 personas)')], default='doble', max_length=20)),
                ('tamaño_cama', models.CharField(choices=[('queen', 'Queen'), ('king', 'King'), ('twin', 'Twin')], default='queen', max_length=20)),
                ('categoria', models.CharField(choices=[('estandar', 'Estándar'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('suite_presidencial', 'Suite Presidencial'), ('estudio', 'Estudio')], default='estandar', max_length=20)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('condicion', models.CharField(choices=[('basica', 'Básica'), ('funcional', 'Funcional'), ('confort', 'Confort'), ('lujo', 'Lujo')], editable=False, max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('limpieza', 'En Limpieza'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20)),
                ('precio_base', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'db_table': 'habitacion',
                'ordering': ['piso', 'numero_habitacion'],
            },
        ),
    ]
