# Generated by Django 5.2.7 on 2025-11-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'ordering': ['piso', 'numero_habitacion'], 'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AddField(
            model_name='habitacion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='condicion',
            field=models.CharField(choices=[('basica', 'Básica'), ('funcional', 'Funcional'), ('confort', 'Confort'), ('lujo', 'Lujo')], default='disponible', editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('limpieza', 'En Limpieza'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='piso',
            field=models.IntegerField(choices=[(1, 'Piso 1'), (2, 'Piso 2'), (3, 'Piso 3'), (4, 'Piso 4'), (5, 'Piso 5'), (6, 'Piso 6'), (7, 'Piso 7'), (8, 'Piso 8')], default=1),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tamaño_cama',
            field=models.CharField(choices=[('queen', 'Queen'), ('king', 'King'), ('twin', 'Twin')], default='queen', max_length=20),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_ocupacion',
            field=models.CharField(choices=[('doble', 'Doble (2 personas)'), ('triple', 'Triple (3 personas)'), ('cuadruple', 'Cuádruple (4 personas)')], default='doble', max_length=20),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='categoria',
            field=models.CharField(choices=[('estandar', 'Estándar'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('suite_presidencial', 'Suite Presidencial'), ('estudio', 'Estudio')], default='estandar', max_length=20),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero_habitacion',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
