# Generated by Django 5.2.7 on 2026-01-10 06:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_salon', '0001_initial'),
        ('salon_eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservasalon',
            options={'ordering': ['-fecha_evento'], 'verbose_name': 'Reserva de Salón', 'verbose_name_plural': 'Reservas de Salones'},
        ),
        migrations.RemoveField(
            model_name='reservasalon',
            name='salon_id',
        ),
        migrations.RemoveField(
            model_name='reservasalon',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='reservasalon',
            name='cantidad_invitados',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Invitados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservasalon',
            name='codigo_evento',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Código de Evento'),
        ),
        migrations.AddField(
            model_name='reservasalon',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='reservasalon',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservasalon',
            name='fecha_evento',
            field=models.DateTimeField(default='2024-01-01 12:00', verbose_name='Fecha y Hora del Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservasalon',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='salon_eventos.salonevento', verbose_name='Salón de Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservasalon',
            name='total_reserva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='reservasalon',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_salon', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservasalon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
