# Generated by Django 5.2.7 on 2025-12-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('costo_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_inicial', models.IntegerField(default=0)),
                ('stock_actual', models.IntegerField(default=0)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vencido', 'Vencido')], default='activo', max_length=10)),
            ],
            options={
                'verbose_name': 'Insumo/Producto',
                'verbose_name_plural': 'Insumos/Productos',
                'db_table': 'insumo_producto',
                'ordering': ['nombre'],
            },
        ),
    ]
