# Generated by Django 5.2.7 on 2025-11-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalonEvento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
            options={
                'db_table': 'salon_eventos',
                'managed': True,
            },
        ),
    ]
