# Generated by Django 5.2.7 on 2025-12-20 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaDinamica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_temporada', models.CharField(choices=[('alta', 'Temporada Alta'), ('media', 'Temporada Media'), ('baja', 'Temporada Baja'), ('evento', 'Evento Especial')], default='media', max_length=20, verbose_name='Tipo de Temporada')),
                ('precio', models.DecimalField(decimal_places=2, default=200.0, max_digits=10, verbose_name='Precio Base de la Temporada')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento (%)')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_dinamicas', to='habitacion.habitacion', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Tarifa Dinámica',
                'verbose_name_plural': 'Tarifas Dinámicas',
                'db_table': 'tarifa_dinamica',
                'ordering': ['habitacion__numero_habitacion', 'fecha_inicio'],
            },
        ),
    ]
