# Generated by Django 5.2.7 on 2025-12-20 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestauranteMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.IntegerField(unique=True)),
                ('capacidad', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1, message='La capacidad debe ser un entero positivo.')])),
                ('ubicacion', models.CharField(choices=[('terraza', 'Terraza'), ('interior', 'Interior')], max_length=50)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('RESERVADA', 'Reservada'), ('LIMPIEZA', 'Limpieza')], default='LIBRE', help_text='Disponibilidad inmediata: Libre, Ocupada, Reservada, Limpieza.', max_length=20)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la mesa está disponible para el sistema (True) o fuera de servicio (False).')),
            ],
            options={
                'verbose_name': 'Mesa de Restaurante',
                'db_table': 'restaurante_mesa',
            },
        ),
    ]
