# Generated by Django 5.2.7 on 2025-11-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionCliente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario_id', models.IntegerField(null=True)),
                ('tipo_atencion', models.TextField(null=True)),
            ],
            options={
                'db_table': 'atencion_cliente',
                'managed': True,
            },
        ),
    ]
