# Generated by Django 5.2.7 on 2025-11-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.TextField(null=True, unique=True)),
                ('nombre', models.TextField(null=True)),
                ('apellido', models.TextField(null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
    ]
