# Generated by Django 5.2.7 on 2025-12-20 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserva_habitacion', '0001_initial'),
        ('servicio_adicional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad')),
                ('notas_cliente', models.TextField(blank=True, null=True, verbose_name='Notas del Cliente (Detalle del Servicio)')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Cobrado')),
                ('reserva_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_solicitados', to='reserva_habitacion.reservahabitacion', verbose_name='Reserva Asociada')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservas_asociadas', to='servicio_adicional.servicioadicional', verbose_name='Servicio Adicional')),
            ],
            options={
                'verbose_name': 'Servicio por Reserva',
                'verbose_name_plural': 'Servicios por Reservas',
                'db_table': 'reserva_servicio',
                'unique_together': {('reserva_habitacion', 'servicio')},
            },
        ),
    ]
