# Generated by Django 5.2.7 on 2025-11-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaSalon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario_id', models.IntegerField(null=True)),
                ('salon_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'reserva_salon',
                'managed': True,
            },
        ),
    ]
