# Generated by Django 5.2.7 on 2025-11-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestauranteMesa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_mesa', models.TextField(null=True)),
                ('capacidad', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'restaurante_mesa',
                'managed': True,
            },
        ),
    ]
