# Generated by Django 5.2.7 on 2025-11-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_habitacion', models.TextField(null=True)),
                ('categoria', models.TextField(null=True)),
            ],
            options={
                'db_table': 'habitacion',
                'managed': True,
            },
        ),
    ]
