# Generated by Django 5.2.7 on 2025-11-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(null=True)),
                ('precio', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'servicio_adicional',
                'managed': True,
            },
        ),
    ]
