# Generated by Django 5.2.7 on 2025-12-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Servicio')),
                ('tipo', models.CharField(choices=[('desayuno', 'Desayuno'), ('traslado', 'Traslado'), ('spa', 'Servicio SPA'), ('mascota', 'Mascota (Pet-Friendly)'), ('otro', 'Otro (Servicio Personalizado)')], default='desayuno', max_length=20, verbose_name='Tipo de Servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Detallada')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base')),
                ('activo', models.BooleanField(default=True, verbose_name='Servicio Activo')),
            ],
            options={
                'verbose_name': 'Servicio Adicional',
                'verbose_name_plural': 'Servicios Adicionales',
                'db_table': 'servicio_adicional',
                'ordering': ['tipo', 'nombre'],
            },
        ),
    ]
