# Generated by Django 5.2.7 on 2025-12-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalonEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('capacidad', models.IntegerField()),
                ('comodidades', models.TextField(help_text='Lista de comodidades (proyector, sonido, etc.)')),
                ('precio_base_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salón de Eventos',
                'db_table': 'salon_evento',
            },
        ),
    ]
