# Generated by Django 5.2.7 on 2025-11-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reserva_habitacion_id', models.IntegerField(null=True)),
                ('servicio_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'reserva_servicio',
                'managed': True,
            },
        ),
    ]
