# Generated by Django 5.2.7 on 2025-11-26 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('RECEPCIONISTA', 'Recepcionista'), ('SUPERVISOR', 'Supervisor'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('documento_identidad', models.CharField(max_length=30, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil_usuario',
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
