# Generated by Django 5.2.7 on 2025-12-20 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_checkin', models.DateField(verbose_name='Fecha Check-In')),
                ('fecha_checkout', models.DateField(verbose_name='Fecha Check-Out')),
                ('huespedes', models.PositiveSmallIntegerField(default=1, verbose_name='Número de Huéspedes')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada (Check-Out)')], default='pendiente', max_length=20, verbose_name='Estado de la Reserva')),
                ('codigo_confirmacion', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código de Confirmación')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total de la Reserva')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='habitacion.habitacion', verbose_name='Habitación Reservada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_habitacion', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reserva de Habitación',
                'verbose_name_plural': 'Reservas de Habitaciones',
                'db_table': 'reserva_habitacion',
                'ordering': ['fecha_checkin', 'estado'],
            },
        ),
    ]
