# Generated by Django 5.2.7 on 2025-12-30 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0002_alter_habitacion_options_habitacion_activa_and_more'),
        ('reserva_habitacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservahabitacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Reserva de Habitación', 'verbose_name_plural': 'Reservas de Habitaciones'},
        ),
        migrations.RemoveField(
            model_name='reservahabitacion',
            name='habitacion_id',
        ),
        migrations.RemoveField(
            model_name='reservahabitacion',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='codigo_confirmacion',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código de Confirmación'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada (Check-Out)')], default='pendiente', max_length=20, verbose_name='Estado de la Reserva'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='fecha_checkin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Check-In'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='fecha_checkout',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Check-Out'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='habitacion.habitacion', verbose_name='Habitación Reservada'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='huespedes',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Número de Huéspedes'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total de la Reserva'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_habitacion', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='reservahabitacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
